// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8rxS1HDqmSp3vXHxONVv_2Hj-BsOJO8',
    appId: '1:427985537921:web:9051d651275a69ab00b680',
    messagingSenderId: '427985537921',
    projectId: 'islamic-sync',
    authDomain: 'islamic-sync.firebaseapp.com',
    databaseURL: 'https://islamic-sync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamic-sync.appspot.com',
    measurementId: 'G-KGLGPTC6ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGx0F7C14fN8jkLPtl6nmRMuEneQ6Jrbg',
    appId: '1:427985537921:android:b7be49b347d4571900b680',
    messagingSenderId: '427985537921',
    projectId: 'islamic-sync',
    databaseURL: 'https://islamic-sync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamic-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHAjCLEjRQc7PrTF4T2YBySP7dxAS-N9I',
    appId: '1:427985537921:ios:0475fd979da8486700b680',
    messagingSenderId: '427985537921',
    projectId: 'islamic-sync',
    databaseURL: 'https://islamic-sync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamic-sync.appspot.com',
    iosBundleId: 'com.example.islamicReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHAjCLEjRQc7PrTF4T2YBySP7dxAS-N9I',
    appId: '1:427985537921:ios:0d4cd7293fdb1a1c00b680',
    messagingSenderId: '427985537921',
    projectId: 'islamic-sync',
    databaseURL: 'https://islamic-sync-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'islamic-sync.appspot.com',
    iosBundleId: 'com.example.islamicReminder.RunnerTests',
  );
}
